[package]
name = "meshido"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = { version = "4.0", default-features = false }
nalgebra = "0.32.3"
